[package]
name = "tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
keyring = { version = "3.6.3", features = ["linux-native"] }
reqwest = { version = "0.13.1", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.148"
tokio.workspace = true
chrono = { workspace = true, features = ["serde"] }
tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
